# Generated by Django 3.2 on 2022-06-12 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='作者姓名')),
                ('avatar', models.ImageField(upload_to='', verbose_name='作者头像')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('birthday', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者信息',
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='出版社名称')),
                ('address', models.TextField(verbose_name='出版社地址')),
            ],
            options={
                'verbose_name': '出版社信息',
                'verbose_name_plural': '出版社信息',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='书籍名称')),
                ('about', models.TextField(verbose_name='书籍简介')),
                ('publication_date', models.DateField(verbose_name='出版日期')),
                ('author', models.ManyToManyField(to='book.Author', verbose_name='作者')),
                ('press', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.press', verbose_name='出版社')),
            ],
            options={
                'verbose_name': '图书信息',
                'verbose_name_plural': '图书信息',
                'ordering': ('-publication_date', 'name'),
            },
        ),
    ]
