version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - CURRENT_ENV=prod
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=django-insecure-zc1=+32*#i%*_o=ryj20^v1$$2sv^#1-dwz)7upuk0qkz-117wn
    depends_on:
      - db
    volumes:
      - .:/Django
      - ./log/nginx/:/var/log/nginx
    command:  # TODO:弃用安装时的nginx.conf，改用自己的nginx.conf
      - sh
      - -c
      - |
        uwsgi --ini uwsgi.ini
        nginx -c /etc/nginx/nginx.conf  
        nginx -s reload