version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
  backend:
    build: .
    restart: always
    environment:
      - Django_ENV=production
    volumes:
      - ./Apps/:/home/django/workspace/Apps/
      - ./daibeisi_tools/:/home/django/workspace/daibeisi_tools/
      - ./DjangoProject/:/home/django/workspace/DjangoProject/
      - ./file/:/home/django/workspace/file/
      - ./middlewares/:/home/django/workspace/middlewares/
      - ./static/:/home/django/workspace/static/
      - ./templates/:/home/django/workspace/templates/
      - ./DjangoProject.conf/:/home/django/workspace/DjangoProject.conf
      - ./gunicorn.conf.py/:/home/django/workspace/gunicorn.conf.py
      - ./manage.py:/home/django/workspace/manage.py
      - ./requirements.txt:/home/django/workspace/requirements.txt
    depends_on:
      - db
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert:/etc/nginx/cert
      - ./file:/usr/share/nginx/file
      - ./nginx/log:/var/log/nginx
    depends_on:
      - backend