version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    restart: always
    command:
      - sh
      - -c
      - |
        nginx -c /etc/nginx/nginx.conf
        nginx -s reload
        uwsgi --ini uwsgi.ini
    volumes:
      - .:/Django
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db