version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
  backend:
    build: .
    restart: always
    environment:
      - Django_ENV=production
    volumes:
      - .:/home/django/workspace/
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert:/etc/nginx/cert
      - ./file:/usr/share/nginx/file
      - ./nginx/log:/var/log/nginx
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "1g"