version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /etc/redis/redis.conf
    privileged: true
  celery:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: Celery -A 项目名 worker -l info & celery -A untitled beat -l info  启动celery和定时任务
    depends_on:
      - redis
  flower:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5555:5555"
    command:  启动异步任务监控
    depends_on:
      - redis
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=DjangoProject.settings.production
    volumes:
      - ./file/:/home/django/workspace/file/
      - ./logs/:/home/django/workspace/logs/
    depends_on:
      - db
      - redis
#  nginx:
#    image: nginx
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    environment:
#      - TZ=Asia/Shanghai
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/cert:/etc/nginx/cert
#      - ./file:/usr/share/nginx/file
#      - ./nginx/log:/var/log/nginx
#    depends_on:
#      - backend