# Generated by Django 3.2 on 2022-05-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
