# Generated by Django 3.2 on 2022-05-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinfo_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
    ]
