# Generated by Django 3.2 on 2022-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='地址'),
        ),
    ]
