# Generated by Django 4.2.4 on 2023-08-31 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="名称"),
                ),
            ],
            options={"verbose_name": "国家", "verbose_name_plural": "国家列表",},
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="部门名称")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="座机电话"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="手机号码"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="部门邮箱"
                    ),
                ),
                ("sequence", models.IntegerField(default=1, verbose_name="排序")),
                ("active", models.BooleanField(default=True, verbose_name="部门状态")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={"verbose_name": "部门", "verbose_name_plural": "部门列表",},
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid1,
                        editable=False,
                        unique=True,
                        verbose_name="用户标识码",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=30, verbose_name="昵称"),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="身份证号",
                    ),
                ),
                (
                    "openid",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="微信openid",
                    ),
                ),
                (
                    "unionid",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="微信unionid",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("female", "女"), ("male", "男"), ("other", "其他")],
                        max_length=10,
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="avatar/avatar.png",
                        upload_to="avatar",
                        verbose_name="头像",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="座机电话"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="手机号码"
                    ),
                ),
                (
                    "dep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.department",
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息表",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="名称"),
                ),
                ("content", models.JSONField(verbose_name="内容")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, to="auth.group", verbose_name="组"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.router",
                        verbose_name="上级路由",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="auth.permission", verbose_name="页面权限"
                    ),
                ),
            ],
            options={"verbose_name": "路由", "verbose_name_plural": "路由列表",},
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="名称")),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.country",
                        verbose_name="国家",
                    ),
                ),
            ],
            options={
                "verbose_name": "省",
                "verbose_name_plural": "省列表",
                "unique_together": {("country", "name")},
            },
        ),
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.userinfo",
                verbose_name="部门负责人",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.department",
                verbose_name="上级部门",
            ),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="名称")),
                (
                    "province",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.province",
                        verbose_name="省",
                    ),
                ),
            ],
            options={
                "verbose_name": "市",
                "verbose_name_plural": "市列表",
                "unique_together": {("province", "name")},
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.city",
                        verbose_name="市",
                    ),
                ),
            ],
            options={
                "verbose_name": "区/县",
                "verbose_name_plural": "区/县列表",
                "unique_together": {("city", "name")},
            },
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                (
                    "area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.area",
                        verbose_name="区/县",
                    ),
                ),
            ],
            options={
                "verbose_name": "乡/镇/街道",
                "verbose_name_plural": "乡/镇/街道列表",
                "unique_together": {("area", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="department", unique_together={("parent", "name")},
        ),
    ]
