# Generated by Django 4.2.4 on 2023-09-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={
                "ordering": ["id"],
                "verbose_name": "人员",
                "verbose_name_plural": "人员列表",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="名称")),
                (
                    "unicode",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="统一社会信用代码"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="座机电话"
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="手机号码"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "公司",
                "verbose_name_plural": "公司列表",
                "unique_together": {("name",)},
            },
        ),
    ]
